require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/form_data", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FormDatum. As you add validations to FormDatum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FormDatum.create! valid_attributes
      get form_data_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      form_datum = FormDatum.create! valid_attributes
      get form_datum_url(form_datum)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_form_datum_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      form_datum = FormDatum.create! valid_attributes
      get edit_form_datum_url(form_datum)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FormDatum" do
        expect {
          post form_data_url, params: { form_datum: valid_attributes }
        }.to change(FormDatum, :count).by(1)
      end

      it "redirects to the created form_datum" do
        post form_data_url, params: { form_datum: valid_attributes }
        expect(response).to redirect_to(form_datum_url(FormDatum.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FormDatum" do
        expect {
          post form_data_url, params: { form_datum: invalid_attributes }
        }.to change(FormDatum, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post form_data_url, params: { form_datum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested form_datum" do
        form_datum = FormDatum.create! valid_attributes
        patch form_datum_url(form_datum), params: { form_datum: new_attributes }
        form_datum.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the form_datum" do
        form_datum = FormDatum.create! valid_attributes
        patch form_datum_url(form_datum), params: { form_datum: new_attributes }
        form_datum.reload
        expect(response).to redirect_to(form_datum_url(form_datum))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        form_datum = FormDatum.create! valid_attributes
        patch form_datum_url(form_datum), params: { form_datum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested form_datum" do
      form_datum = FormDatum.create! valid_attributes
      expect {
        delete form_datum_url(form_datum)
      }.to change(FormDatum, :count).by(-1)
    end

    it "redirects to the form_data list" do
      form_datum = FormDatum.create! valid_attributes
      delete form_datum_url(form_datum)
      expect(response).to redirect_to(form_data_url)
    end
  end
end
